sylius_twig_hooks:
    hooks:
        sylius_admin.product_variant.update.content.form.side_navigation:
            - _name: mollie_recurring
              enabled: false
        'sylius_shop.product.show.content.info.overview.images':
            main_image:
                enabled: false
            main_image_using_component:
                component: 'app:product:images'
                props:
                    product: '@=_context.product'
                    template: 'bundles/SyliusShopBundle/product/show/content/info/overview/images/main_image.html.twig'
                priority: 0
        sylius_shop.shared.order.show.summary.table.header:
            -   _name: recurring
                enabled: false
        sylius_shop.shared.order.show.summary.table.body:
            - _name: recurring
              enabled: false
        sylius_admin.security.login.page.content.form:
            - _name: submit
              template: 'admin/security/login/page/content/form/submit.html.twig'
        sylius_admin.dashboard.index.content:
            - _name: chart
              template: 'admin/chart/index.html.twig'
        sylius_admin.product_variant.create.content.form.sections.general.body.options:
            - _name: color
              template: 'admin/color/color.html.twig'
        sylius_shop.cart.index.content.form.sections.general.items.head:
            - _name: recurring
              enabled: false
            - _name: remove
              priority: -100
            - _name: colgroup
              template: 'shop/cart/colgroup.html.twig'
              priority: 400
        sylius_shop.cart.index.content.form.sections.general.items.body:
            - _name: recurring_settings
              enabled: false
            - _name: remove
              template: 'shop/cart/index/content/form/sections/general/items/body/remove.html.twig'
              priority: -100
        sylius_shop.base.header.top_bar:
            - _name: info_message
              template: 'shop/top_bar/info_message.html.twig'
              priority: 200
        'sylius_admin.overview3d.index':
            sidebar:
                template: '@SyliusAdmin/shared/crud/common/sidebar.html.twig'
                priority: 200
            navbar:
                template: '@SyliusAdmin/shared/crud/common/navbar.html.twig'
                priority: 100
            content:
                template: '@SyliusAdmin/shared/crud/common/content.html.twig'
                priority: 0
        'sylius_admin.overview3d.index.content':
            header:
                template: '@SyliusAdmin/shared/crud/common/content/header.html.twig'
                priority: 200
            grid:
                enabled: false
            latest_statistics:
                configuration:
                    products: products
                template: 'admin/3d_canvas/3d_overview.html.twig'
                priority: 0
        'sylius_admin.over.index.content':
            flashes:
                template: '@SyliusAdmin/shared/crud/common/content/flashes.html.twig'
                priority: 300
            header:
                template: '@SyliusAdmin/shared/crud/common/content/header.html.twig'
                priority: 200
            grid:
                template: '@SyliusAdmin/shared/crud/index/content/grid.html.twig'
                priority: 100
            footer:
                template: '@SyliusAdmin/shared/crud/common/content/footer.html.twig'
                priority: -100
        'sylius_admin.over.index.content.header':
            breadcrumbs:
#                enabled: false
                template: 'admin/breadcrumbs.html.twig'
                priority: 0
            title_block:
#                enabled: false
                template: '@SyliusAdmin/shared/crud/common/content/header/title_block.html.twig'
                priority: 0
        'sylius_admin.overview3d.index.content.header.title_block':
            title:
                template: 'admin/title.html.twig'
        'sylius_admin.over.index.content.grid':
            filters:
                template: '@SyliusAdmin/shared/crud/index/content/grid/filters.html.twig'
                priority: 200
            data_table:
                template: '@SyliusAdmin/shared/crud/index/content/grid/data_table.html.twig'
                priority: 100
            no_data_block:
                template: '@SyliusAdmin/shared/crud/index/content/grid/no_results.html.twig'
                priority: 0
        sylius_admin.product.update.content.form.sections.media:
            threemodel:
                template: 'admin/threemodel.html.twig'
                priority: 100
        sylius_admin.product.create.content.form.sections.media:
            threemodel:
                template: 'admin/threemodel.html.twig'
                priority: 100
