twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/templates': 'SyliusAdmin'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Twig\Extra\Intl\IntlExtension: ~
    Twig\Extra\String\StringExtension: ~

when@test_cached:
    twig:
        strict_variables: true
